### ISSUE TITLE
Parem viis külastusstatistika visualiseerimiseks

### ISSUE THREAD

**Issue by kmteras** [Teras23/poll_application#32]
Tuleks välja jätta mõned mõttetud väärtused (uknown).
Pie charti asemel tuleb leida mingi parem alternatiiv.
Asukohad kaardi peale?
Külastuste kuupäeva jaoks histogram.

**Comment by andreasvija** [comment]
Graafikute asetuse responsiveness võiks anda iga nädal pool punkti "Aknasuuruste tugi" eest juurde 2. etapi kommentaari järgi.
